// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://rriukgdpjlemgalttztd.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InJyaXVrZ2RwamxlbWdhbHR0enRkIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTU3MTkxODAsImV4cCI6MjA3MTI5NTE4MH0.wreevP8VyVc29p9UM0rYSRPUsBgm88tVp7dEe0ML4lg";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});